# Load necessary libraries
library(ggtree)
library(treeio)
library(ape)
library(ggplot2)

# Set working directory to the folder containing the alignment file
setwd("/Users/katiaavinapadilla/Desktop/SECUENCIASDEPSOMAGENERIKA/")

# Read the consensus tree generated by IQ-TREE2
tree <- read.tree("Resultado_Alignment.aln.contree")

# Create the phylogenetic tree visualization with bootstrap values using ggtree
p <- ggtree(tree, layout = "rectangular") +
  geom_tree(aes(color = branch.length), size = 0.5) + # Color branches by length
  scale_color_viridis_c() + # Professional color scale (viridis)
  theme_minimal() + 
  theme(panel.background = element_rect(fill = "white", color = "white"),
        plot.background = element_rect(fill = "white", color = "white"),
        plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
        legend.position = "right") +
  geom_tiplab(aes(label = label), size = 2.5, color = "darkblue", hjust = -0.2) + # Node labels
  geom_text2(aes(subset = !is.na(as.numeric(label)) & as.numeric(label) >= 70, # Show bootstrap values >= 70
                 label = label), color = "red", hjust = -0.2, size = 3) + # Highlight high bootstrap values in red
  ggtitle("Phylogenetic Tree of ToBRFV Isolates") # Title of the plot

# Display the plot
print(p)
